export default [
    {
        "img_path": "./images/tRacketImage1-4x3.jpg",
        "img_alt": "tRacket screenshot",
        "title": "tRacket",
        "tagline": "Racket sports tracking tool",
        "description_1": "By far my most ambitious project, tRacket is a full-stack web app that tracks various racket sport matches (namely players scores and heart rates) and graphs/stores said matches for later review.",
        "description_2": "I implemented flexible authentication using JWTs and bcrypt to ensure a seamless user experience, and I gained solid experience with AWS when deploying the backend via EC2 + RDS, and the frontend via S3 + Cloudfront CDN.",
        "icon_1_path": "./icons/react.svg",
        "icon_1_alt": "react logo",
        "icon_2_path": "./icons/nodejs.svg",
        "icon_2_alt": "node.js logo",
        "icon_3_path": "./icons/express.svg",
        "icon_3_alt": "express.js logo",
        "icon_4_path": "./icons/postgres.svg",
        "icon_4_alt": "postgreSQL logo",
        "icon_5_path": "./icons/aws.svg",
        "icon_5_alt": "AWS logo",
        "live_url": "https://t-racket.com",
        "github_url": "https://github.com/wallisCodes/table-tennis-scorer"
    },
    {
        "img_path": "./images/SchedulerImage1-4x3.jpg",
        "img_alt": "Tennis scheduler screenshot",
        "title": "Tennis Scheduler",
        "tagline": "Tennis scheduling tool for my local club",
        "description_1": "Organisational tool to schedule tennis matches supporting up to 40 players at once across 8 courts, during club hours.",
        "description_2": "Through the creation of a bespoke scheduling algorithm utilising various forms I learned a lot about array manipulation, react hooks and props.",
        "icon_1_path": "./icons/react.svg",
        "icon_1_alt": "react logo",
        "icon_2_path": "./icons/tailwindcss.svg",
        "icon_2_alt": "tailwind logo",
        "icon_3_path": "./icons/html.svg",
        "icon_3_alt": "html logo",
        "icon_4_path": "./icons/css.svg",
        "icon_4_alt": "css logo",
        "live_url": "https://tennis-schedule.net",
        "github_url": "https://github.com/wallisCodes/tennis-scheduler"
    },
    {
        "img_path": "./images/PortfolioImage1-4x3.jpg",
        "img_alt": "Portfolio website screenshot",
        "title": "Portfolio",
        "tagline": "Website to showcase projects and skills",
        "description_1": "It was my first time using react and tailwind. The idea was to learn the basics of these technologies before moving on to more challenging projects.",
        "description_2": "I learned about component based architecture in react and the benefits of tailwind css, especially in team environments. I also gained familiarity with the vite build tool and importing custom packages using npm.",
        "icon_1_path": "./icons/react.svg",
        "icon_1_alt": "react logo",
        "icon_2_path": "./icons/tailwindcss.svg",
        "icon_2_alt": "tailwind logo",
        "icon_3_path": "./icons/html.svg",
        "icon_3_alt": "html logo",
        "icon_4_path": "./icons/css.svg",
        "icon_4_alt": "css logo",
        "github_url": "https://github.com/wallisCodes/professional-portfolio"
    },
    {
        "img_path": "./images/Avenue136Image1-4x3.jpg",
        "img_alt": "Avenue136 hairdressing website screenshot",
        "title": "Avenue136",
        "tagline": "Hairdressing website for local business",
        "description_1": "My first website built using vanilla HTML, CSS and Javascript. Fully responsive, static site, hosted on Cloudflare Pages.",
        "description_2": "Purposefully designed from the ground up to reinforce the frontend basics before moving on to more advanced technologies/frameworks.",
        "icon_1_path": "./icons/html.svg",
        "icon_1_alt": "html logo",
        "icon_2_path": "./icons/css.svg",
        "icon_2_alt": "css logo",
        "icon_3_path": "./icons/javascript.svg",
        "icon_3_alt": "javascript logo",
        "live_url": "https://avenue136.co.uk/",
        "github_url": "https://github.com/wallisCodes/Avenue136"
    }    
]