export default [
    {
        "img_path": "../src/assets/images/tRacketImage1-4x3.jpg",
        "img_alt": "Racketlon scorer screenshot",
        "title": "Racketlon Scorer",
        "tagline": "Racketlon scoring tool",
        "description_1": "Full-stack web app that tracks various racket sport matches (scoring and players heart rates) and graphs the data in real-time.",
        "description_2": "Matches are saved to a postgreSQL database for later display/analysis via player dashboard.",
        "icon_1_path": "../src/assets/icons/react.svg",
        "icon_1_alt": "react logo",
        "icon_2_path": "../src/assets/icons/nodejs.svg",
        "icon_2_alt": "node.js logo",
        "icon_3_path": "../src/assets/icons/express.svg",
        "icon_3_alt": "express.js logo",
        "icon_4_path": "../src/assets/icons/postgres.svg",
        "icon_4_alt": "postgreSQL logo",
        "live_url": "https://walliscodes.github.io/table-tennis-scorer/",
        "github_url": "https://github.com/wallisCodes/table-tennis-scorer"
    },
    {
        "img_path": "../src/assets/images/SchedulerImage1-4x3.jpg",
        "img_alt": "Tennis scheduler screenshot",
        "title": "Tennis Scheduler",
        "tagline": "Tennis scheduling tool for my local club",
        "description_1": "Organisational tool to schedule tennis matches supporting up to 40 players at once across 8 courts, during club hours.",
        "description_2": "Through the creation of a bespoke scheduling algorithm utilising various forms I learned a lot about array manipulation, React hooks and props.",
        "icon_1_path": "../src/assets/icons/react.svg",
        "icon_1_alt": "react logo",
        "icon_2_path": "../src/assets/icons/tailwindcss.svg",
        "icon_2_alt": "tailwind logo",
        "icon_3_path": "../src/assets/icons/html.svg",
        "icon_3_alt": "html logo",
        "icon_4_path": "../src/assets/icons/css.svg",
        "icon_4_alt": "css logo",
        "live_url": "https://tennis-schedule.net",
        "github_url": "https://github.com/wallisCodes/tennis-scheduler"
    },
    {
        "img_path": "../src/assets/images/PortfolioImage1-4x3.jpg",
        "img_alt": "Portfolio website screenshot",
        "title": "Portfolio",
        "tagline": "Website to showcase projects and skills",
        "description_1": "It was my first time using both react and tailwind for this project. Again fully responsive, this time hosted on Github Pages.",
        "description_2": "The idea was to start with a simple portfolio website to learn the basics of these technologies before moving on to more challenging projects.",
        "icon_1_path": "../src/assets/icons/react.svg",
        "icon_1_alt": "react logo",
        "icon_2_path": "../src/assets/icons/tailwindcss.svg",
        "icon_2_alt": "tailwind logo",
        "icon_3_path": "../src/assets/icons/html.svg",
        "icon_3_alt": "html logo",
        "icon_4_path": "../src/assets/icons/css.svg",
        "icon_4_alt": "css logo",
        "github_url": "https://github.com/wallisCodes/professional-portfolio"
    },
    {
        "img_path": "../src/assets/images/Avenue136Image1-4x3.jpg",
        "img_alt": "Avenue136 hairdressing website screenshot",
        "title": "Avenue136",
        "tagline": "Hairdressing website for local business",
        "description_1": "My first website built using vanilla HTML, CSS and Javascript. Fully responsive, static site, hosted on Cloudflare Pages.",
        "description_2": "Purposefully designed from the ground up to reinforce the frontend basics before moving on to more advanced technologies/frameworks.",
        "icon_1_path": "../src/assets/icons/html.svg",
        "icon_1_alt": "html logo",
        "icon_2_path": "../src/assets/icons/css.svg",
        "icon_2_alt": "css logo",
        "icon_3_path": "../src/assets/icons/javascript.svg",
        "icon_3_alt": "javascript logo",
        "live_url": "https://avenue136.co.uk/",
        "github_url": "https://github.com/wallisCodes/Avenue136"
    }    
]